group: Engine
depends_on:
  - image-build
steps:
- label: ":nvidia: (H200 MIG 18GB) Engine Core"
  key: engine
  timeout_in_minutes: 30
  device: h200_18gb
  source_file_dependencies:
  - vllm/compilation/
  - vllm/config/
  - vllm/engine/
  - vllm/entrypoints/logger.py
  - vllm/envs.py
  - vllm/logger.py
  - vllm/logging_utils/
  - vllm/platforms/
  - vllm/sequence.py
  - vllm/triton_utils/
  - vllm/utils/
  - tests/engine
  - tests/test_sequence
  - tests/test_config
  - tests/test_logger
  - tests/test_vllm_port
  - tests/jit_monitor/test_hooks.py
  - tests/jit_monitor/test_hooks_gpu.py
  commands:
  - pytest -v -s engine test_sequence.py test_config.py test_logger.py test_vllm_port.py jit_monitor/test_hooks.py jit_monitor/test_hooks_gpu.py
  mirror:
    amd:
      label: ":amd: (MI355 DPX) Engine Core"
      dind: false
      device: mi355_dpx
      timeout_in_minutes: 40
      depends_on:
      - image-build-amd
